# Generated by Django 4.0.6 on 2022-08-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_status_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_text', models.TextField()),
                ('com_date', models.DateTimeField(auto_now=True)),
                ('com_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
            ],
        ),
    ]
