# Generated by Django 4.0.6 on 2022-08-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecards',
            options={'verbose_name': 'PriceCard', 'verbose_name_plural': 'PriceCards'},
        ),
        migrations.AlterModelOptions(
            name='servicetable',
            options={'verbose_name': 'PriceTable', 'verbose_name_plural': 'PriceTable'},
        ),
    ]
